defaults:
  - data: motion_mimic
  - model: fsq
  - optim: adam
  - train: default
  - log: default
  - _self_

hydra:
  run:
    dir: ${log.root}/${now:%Y%m%d_%H%M%S}
  output_subdir: null
  job:
    chdir: false
